name: pipeline_ci

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-test:
    name: Build e testes unitários
    runs-on: windows-latest

    steps:
    - name: Checkout da branch
      uses: actions/checkout@v4

    - name: Instalar o .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restaurar dependências
      run: dotnet restore

    - name: Build da aplicação
      run: dotnet build --no-restore

    - name: Executando testes unitários
      run: dotnet test --no-build --verbosity normal

  build-push-docker-image:
    needs: build-test
    name: Fazer login no Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout da branch
      uses: actions/checkout@v4

    - name: Login Docker
      uses: docker/login-action@v3.3.0
      with:
        username: 'dco1993'
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
    - name: Build e push da imagem Docker
      uses: docker/build-push-action@v6.7.0
      with:
        context: .
        tags: 'dco1993/fiap-rm356750:latest'
        push: true
