name: Teste criar imagem no Docker Hub

on:
  push:
    branches: [develop]

jobs:
  job:
    name: Fazer login no Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Step 1
      uses: actions/checkout@v2

    - name: Login Docker
      uses: docker/login-action@v3.3.0
      with:
        username: 'dco1993'
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
